import * as assert from "node:assert";
import { spawnSync } from "node:child_process";
import * as path from "node:path";

describe("resource search service", () => {
  it("caches prepared responses, scopes projects, and preserves candidates", () => {
    const modulePath = path.join(
      process.cwd(),
      "out",
      "src",
      "services",
      "resourceSearchService.js"
    );
    const script = [
      "const assert = require('node:assert');",
      "const Module = require('node:module'); const originalLoad = Module._load;",
      "const modulePath = process.argv[1];",
      "let findCalls = 0; let folderListener; let folderSubscriptionDisposed = false;",
      "const uri = value => ({ fsPath: value, path: value, toString: () => `file:///${value}` });",
      "const vscode = {",
      "  workspace: {",
      "    workspaceFolders: [{ uri: uri('workspace') }],",
      "    findFiles: async () => { findCalls++; return [uri('workspace/rsgl.config.json')]; },",
      "    onDidChangeWorkspaceFolders: listener => {",
      "      folderListener = listener;",
      "      return { dispose: () => { folderSubscriptionDisposed = true; } };",
      "    }",
      "  }",
      "};",
      "Module._load = function(request, ...args) {",
      "  return request === 'vscode' ? vscode : originalLoad.call(this, request, ...args);",
      "};",
      "const { ResourceSearchService } = require(modulePath);",
      "const target = { kind: 'model', id: 'demo:block/stone' };",
      "const producer = {",
      "  producerId: 'physical:model:demo:block/stone', providerId: 'physical',",
      "  projectId: 'project', layerId: 'local', layerRole: 'local', origin: 'physical',",
      "  logicalKeys: [target], sourceOrigins: [],",
      "  physicalOrigins: [{ uri: 'file:///workspace/assets/demo/models/block/stone.json', origin: 'physical' }],",
      "  materializationState: 'handwritten', outputPath: 'assets/demo/models/block/stone.json', revision: 'r1'",
      "};",
      "const inventory = {",
      "  resources: [{ target, producer, candidates: [producer], resolutionStatus: 'conflict' }],",
      "  coverage: 'authoritative'",
      "};",
      "let service; let ensureCalls = 0; const inventoryCalls = []; let invalidations = 0;",
      "const navigation = {",
      "  ensureProjectForUri: async (_uri, options) => {",
      "    ensureCalls++;",
      "    service.resourcesChanged({",
      "      kind: 'invalidation', projectId: 'project', providerIds: ['rsgl'], causeId: options.causeId",
      "    });",
      "    return { context: { projectId: 'project' }, coverage: 'authoritative' };",
      "  },",
      "  getKnownResources: async (kinds, options) => {",
      "    inventoryCalls.push({ kinds: [...kinds], projectIds: [...(options.projectIds || [])] });",
      "    return inventory;",
      "  }",
      "};",
      "service = new ResourceSearchService(navigation);",
      "service.onDidInvalidate(() => { invalidations++; });",
      "const request = { query: 'stone', kinds: ['model'], limit: 20 };",
      "const turn = () => new Promise(resolve => setImmediate(resolve));",
      "(async () => {",
      "  const [first, repeated] = await Promise.all([",
      "    service.search(request),",
      "    service.search(request)",
      "  ]);",
      "  const equivalent = await service.search({ query: ' ＳＴＯＮＥ ', kinds: ['model', 'model'], limit: 20.9 });",
      "  assert.strictEqual(repeated, first, 'concurrent identical requests should share one response');",
      "  assert.strictEqual(equivalent, first, 'normalized equivalent requests should share a cache entry');",
      "  assert.strictEqual(first.matches[0].candidates[0], producer);",
      "  assert.strictEqual(findCalls, 1);",
      "  assert.strictEqual(ensureCalls, 2);",
      "  assert.deepStrictEqual(inventoryCalls, [",
      "    { kinds: ['blockstate', 'model', 'texture'], projectIds: ['project'] }",
      "  ], 'provider changes requested by this inventory load are already reflected and must not retry');",
      "  assert.notStrictEqual(await service.search({ ...request, limit: 1 }), first);",
      "  assert.strictEqual(inventoryCalls.length, 1, 'different queries should reuse the prepared inventory');",
      "  service.resourcesChanged();",
      "  await turn();",
      "  assert.strictEqual(inventoryCalls.length, 1, 'invalidation alone must never start background inventory work');",
      "  const afterResourceChange = await service.search(request);",
      "  assert.notStrictEqual(afterResourceChange, first, 'inventory invalidation should clear response cache');",
      "  assert.strictEqual(invalidations, 1, 'only external resource changes should invalidate consumers');",
      "  assert.strictEqual(findCalls, 1, 'ordinary resource changes reuse project discovery');",
      "  assert.strictEqual(ensureCalls, 2, 'ordinary resource changes reuse resolved project IDs');",
      "  assert.strictEqual(inventoryCalls.length, 2);",
      "  service.invalidateProjectMetadata('workspace/assets/demo/models/block/stone.json', 'change');",
      "  assert.strictEqual(await service.search(request), afterResourceChange, 'ordinary paths keep cached discovery and responses');",
      "  service.invalidateProjectMetadata('workspace/pack.mcmeta', 'change');",
      "  await service.search(request);",
      "  assert.strictEqual(findCalls, 1, 'metadata content changes reuse project discovery');",
      "  assert.strictEqual(ensureCalls, 4, 'metadata content changes re-resolve cached anchors');",
      "  assert.strictEqual(inventoryCalls.length, 3);",
      "  service.invalidateProjectMetadata('workspace/pack.mcmeta', 'create');",
      "  await service.search(request);",
      "  assert.strictEqual(findCalls, 2, 'structural project metadata changes invalidate anchor discovery');",
      "  assert.strictEqual(ensureCalls, 6);",
      "  assert.strictEqual(inventoryCalls.length, 4);",
      "  service.invalidateProjectDiscovery();",
      "  await service.search(request);",
      "  assert.strictEqual(findCalls, 3, 'explicit project discovery invalidation rescans anchors');",
      "  assert.strictEqual(ensureCalls, 8);",
      "  assert.strictEqual(inventoryCalls.length, 5);",
      "  folderListener();",
      "  await service.search(request);",
      "  assert.strictEqual(findCalls, 4, 'workspace-folder changes invalidate anchor discovery');",
      "  assert.strictEqual(ensureCalls, 10);",
      "  assert.strictEqual(inventoryCalls.length, 6);",
      "  service.resourcesChanged({ kind: 'removal', projectId: 'project', providerIds: ['physical'] });",
      "  await service.search(request);",
      "  assert.strictEqual(findCalls, 4, 'project removal should reuse cached anchors');",
      "  assert.strictEqual(ensureCalls, 12, 'project removal should re-resolve project IDs');",
      "  assert.strictEqual(inventoryCalls.length, 7);",
      "  service.dispose();",
      "  assert.strictEqual(folderSubscriptionDisposed, true);",
      "})().catch(error => { console.error(error); process.exitCode = 1; });"
    ].join("\n");

    const result = spawnSync(process.execPath, ["-e", script, modulePath], {
      encoding: "utf8"
    });

    assert.strictEqual(result.status, 0, result.stderr);
  });

  it("retries an in-flight inventory invalidated by a real structural change", () => {
    const modulePath = path.join(
      process.cwd(),
      "out",
      "src",
      "services",
      "resourceSearchService.js"
    );
    const script = [
      "const assert = require('node:assert');",
      "const Module = require('node:module'); const originalLoad = Module._load;",
      "const modulePath = process.argv[1];",
      "const uri = value => ({ fsPath: value, path: value, toString: () => `file:///${value}` });",
      "const vscode = { workspace: {",
      "  workspaceFolders: [{ uri: uri('workspace') }],",
      "  findFiles: async () => [],",
      "  onDidChangeWorkspaceFolders: () => ({ dispose() {} })",
      "} };",
      "Module._load = function(request, ...args) {",
      "  return request === 'vscode' ? vscode : originalLoad.call(this, request, ...args);",
      "};",
      "const { ResourceSearchService } = require(modulePath);",
      "const target = { kind: 'model', id: 'demo:block/stone' };",
      "const producer = {",
      "  producerId: 'physical:model:demo:block/stone', providerId: 'physical',",
      "  projectId: 'project', layerId: 'local', layerRole: 'local', origin: 'physical',",
      "  logicalKeys: [target], sourceOrigins: [], physicalOrigins: [],",
      "  materializationState: 'handwritten', revision: 'r1'",
      "};",
      "const inventory = {",
      "  resources: [{ target, producer, candidates: [producer], resolutionStatus: 'resolved' }],",
      "  coverage: 'authoritative'",
      "};",
      "let resolveFirst; let announceFirst;",
      "const firstLoadStarted = new Promise(resolve => { announceFirst = resolve; });",
      "let inventoryCalls = 0;",
      "const navigation = {",
      "  ensureProjectForUri: async () => ({ context: { projectId: 'project' }, coverage: 'authoritative' }),",
      "  getKnownResources: async () => {",
      "    inventoryCalls++;",
      "    if (inventoryCalls === 1) {",
      "      announceFirst();",
      "      return new Promise(resolve => { resolveFirst = resolve; });",
      "    }",
      "    return inventory;",
      "  }",
      "};",
      "const service = new ResourceSearchService(navigation);",
      "const request = { query: 'stone', kinds: ['model'], limit: 20 };",
      "const turn = () => new Promise(resolve => setImmediate(resolve));",
      "(async () => {",
      "  const obsoleteController = new AbortController();",
      "  const obsoleteSearch = service.search({ ...request, query: 'obsolete', signal: obsoleteController.signal });",
      "  const obsoleteRejection = assert.rejects(obsoleteSearch, error => error?.name === 'AbortError');",
      "  await firstLoadStarted;",
      "  obsoleteController.abort();",
      "  const firstSearch = service.search(request);",
      "  service.resourcesChanged({",
      "    kind: 'replacement', projectId: 'project', providerIds: ['rsgl'], causeId: Symbol('external')",
      "  });",
      "  resolveFirst(inventory);",
      "  const first = await firstSearch;",
      "  await obsoleteRejection;",
      "  assert.strictEqual(first.matches.length, 1);",
      "  assert.strictEqual(inventoryCalls, 2, 'the active user search should retry its stale inventory');",
      "  const second = await service.search(request);",
      "  assert.strictEqual(inventoryCalls, 2, 'the current response should populate the cache');",
      "  assert.strictEqual(second, first);",
      "  service.dispose();",
      "  let churnService; let churnCalls = 0;",
      "  const churnNavigation = {",
      "    ensureProjectForUri: navigation.ensureProjectForUri,",
      "    getKnownResources: async () => {",
      "      churnCalls++;",
      "      churnService.resourcesChanged({",
      "        kind: 'replacement', projectId: 'project', providerIds: ['rsgl'], causeId: Symbol('external')",
      "      });",
      "      return inventory;",
      "    }",
      "  };",
      "  churnService = new ResourceSearchService(churnNavigation);",
      "  const bounded = await churnService.search(request);",
      "  assert.strictEqual(bounded.matches.length, 1);",
      "  assert.strictEqual(churnCalls, 3, 'continuous external churn must not create an unbounded retry loop');",
      "  await churnService.search(request);",
      "  assert.strictEqual(churnCalls, 6, 'an unstable response must not populate the cache');",
      "  churnService.dispose();",
      "})().catch(error => { console.error(error); process.exitCode = 1; });"
    ].join("\n");

    const result = spawnSync(process.execPath, ["-e", script, modulePath], {
      encoding: "utf8"
    });

    assert.strictEqual(result.status, 0, result.stderr);
  });
});
