import { resolveFreshCompiledModule } from "../../../test/helpers/compiledHarness";
import {
  assertTestProcessStatus,
  defaultTestProcessMochaTimeoutMs,
  runTestProcessSync
} from "../../../test/helpers/testProcess";

describe("resource graph search quick pick", function () {
  this.timeout(defaultTestProcessMochaTimeoutMs);

  it("ignores stale requests and focuses the accepted resource", () => {
    const modulePath = resolveFreshCompiledModule("src/views/resourceGraphSearchQuickPick.ts");
    const script = [
      "const assert = require('node:assert/strict');",
      "const Module = require('node:module'); const originalLoad = Module._load;",
      "const modulePath = process.argv[1];",
      "const format = (value, args) => args.reduce((text, arg, index) => text.replace(`{${index}}`, String(arg)), value);",
      "function emitter() {",
      "  const listeners = new Set();",
      "  return {",
      "    event: listener => { listeners.add(listener); return { dispose: () => listeners.delete(listener) }; },",
      "    fire: value => { for (const listener of [...listeners]) listener(value); }",
      "  };",
      "}",
      "let picker;",
      "function createQuickPick() {",
      "  const change = emitter(); const trigger = emitter(); const accept = emitter(); const hide = emitter();",
      "  picker = {",
      "    value: '', items: [], activeItems: [], selectedItems: [], buttons: [], busy: false, disposed: false,",
      "    onDidChangeValue: change.event, onDidTriggerButton: trigger.event,",
      "    onDidAccept: accept.event, onDidHide: hide.event,",
      "    show() {}, hide() { hide.fire(); }, dispose() { this.disposed = true; },",
      "    change: change.fire, trigger: trigger.fire, accept: accept.fire",
      "  };",
      "  return picker;",
      "}",
      "class ThemeIcon { constructor(id) { this.id = id; } }",
      "const vscode = {",
      "  ThemeIcon,",
      "  QuickPickItemKind: { Separator: -1 },",
      "  l10n: { t: (value, ...args) => format(value, args) },",
      "  window: { createQuickPick }",
      "};",
      "Module._load = function(request, ...args) {",
      "  return request === 'vscode' ? vscode : originalLoad.call(this, request, ...args);",
      "};",
      "const target = id => ({ kind: 'model', id });",
      "const match = id => {",
      "  const logical = target(id);",
      "  return {",
      "    kind: 'model', id, target: logical, resolutionStatus: 'resolved',",
      "    materializationState: 'handwritten',",
      "    navigation: { kind: 'producer', producerId: `physical:${id}`, target: logical },",
      "    producer: {",
      "      producerId: `physical:${id}`, providerId: 'physical', projectId: 'project',",
      "      layerId: 'local', layerRole: 'local', origin: 'physical', logicalKeys: [logical],",
      "      sourceOrigins: [], physicalOrigins: [], materializationState: 'handwritten', revision: 'r1'",
      "    }",
      "  };",
      "};",
      "let resolveOld; const oldResult = new Promise(resolve => { resolveOld = resolve; });",
      "const calls = []; const requests = [];",
      "let invalidateListener;",
      "const search = {",
      "  onDidInvalidate: listener => { invalidateListener = listener; return { dispose: () => { invalidateListener = undefined; } }; },",
      "  search: request => {",
      "  requests.push(request);",
      "  calls.push(request.query);",
      "  return request.query === 'old'",
      "    ? oldResult",
      "    : Promise.resolve({ matches: [match('demo:new')], coverage: request.query === 'later' ? 'partial' : 'authoritative' });",
      "} };",
      "const selected = [];",
      "const { ResourceGraphSearchQuickPick } = require(modulePath);",
      "const controller = new ResourceGraphSearchQuickPick(search, value => selected.push(value), 0);",
      "const wait = ms => new Promise(resolve => setTimeout(resolve, ms));",
      "const waitFor = async (predicate, label) => {",
      "  const deadline = Date.now() + 1000;",
      "  while (!predicate()) {",
      "    if (Date.now() >= deadline) throw new Error(`Timed out waiting for ${label}`);",
      "    await wait(5);",
      "  }",
      "};",
      "(async () => {",
      "  controller.show();",
      "  picker.value = 'old'; picker.change();",
      "  await waitFor(() => calls.length === 1, 'the initial search');",
      "  assert.deepStrictEqual(calls, ['old']);",
      "  picker.value = 'new'; picker.change();",
      "  assert.strictEqual(requests[0].signal.aborted, true, 'a superseded query should stop before filtering the shared inventory');",
      "  await waitFor(() => calls.length === 2, 'the replacement search');",
      "  assert.deepStrictEqual(calls, ['old', 'new']);",
      "  assert.ok(picker.items.some(item => item.match?.id === 'demo:new'));",
      "  assert.strictEqual(picker.activeItems[0]?.match?.id, 'demo:new');",
      "  resolveOld({ matches: [match('demo:old')], coverage: 'authoritative' });",
      "  await wait(0);",
      "  assert.strictEqual(picker.items.some(item => item.match?.id === 'demo:old'), false);",
      "  const staleItem = picker.items.find(item => item.match?.id === 'demo:new');",
      "  picker.value = 'later'; picker.change();",
      "  assert.strictEqual(picker.items.some(item => item.match), false, 'changing the query must immediately remove selectable stale items');",
      "  picker.selectedItems = [staleItem]; picker.accept();",
      "  assert.deepStrictEqual(selected, [], 'an item rendered for an older request must not be accepted');",
      "  await waitFor(() => calls.length === 3, 'the later search');",
      "  assert.deepStrictEqual(calls, ['old', 'new', 'later']);",
      "  assert.ok(picker.items.some(item => item.match?.id === 'demo:new'));",
      "  assert.strictEqual(picker.items[0].kind, -1, 'coverage should be presented as a non-selectable separator');",
      "  assert.strictEqual(picker.activeItems[0]?.match?.id, 'demo:new');",
      "  invalidateListener();",
      "  assert.strictEqual(picker.items.some(item => item.match), false, 'inventory invalidation must immediately retire rendered matches');",
      "  await waitFor(() => calls.length === 4, 'the invalidation refresh');",
      "  assert.deepStrictEqual(calls, ['old', 'new', 'later', 'later']);",
      "  picker.selectedItems = [picker.items.find(item => item.match?.id === 'demo:new')];",
      "  picker.accept();",
      "  assert.deepStrictEqual(selected.map(item => item.id), ['demo:new']);",
      "  assert.strictEqual(picker.disposed, true);",
      "  controller.dispose();",
      "})().catch(error => { console.error(error); process.exitCode = 1; });"
    ].join("\n");

    const result = runTestProcessSync(process.execPath, ["-e", script, modulePath]);

    assertTestProcessStatus(result);
  });
});
