import { resolveFreshCompiledModule } from "../../../test/helpers/compiledHarness";
import {
  assertTestProcessStatus,
  defaultTestProcessMochaTimeoutMs,
  runTestProcessSync
} from "../../../test/helpers/testProcess";

describe("resource graph tree provider", function () {
  this.timeout(defaultTestProcessMochaTimeoutMs);

  it("keeps a searched focus stable across active-editor changes", () => {
    const modulePath = resolveFreshCompiledModule("src/views/resourceGraphTree.ts");
    const script = [
      "const assert = require('node:assert/strict');",
      "const Module = require('node:module'); const originalLoad = Module._load;",
      "const modulePath = process.argv[1];",
      "class EventEmitter {",
      "  constructor() { this.listeners = new Set(); this.event = listener => {",
      "    this.listeners.add(listener); return { dispose: () => this.listeners.delete(listener) };",
      "  }; }",
      "  fire(value) { for (const listener of [...this.listeners]) listener(value); }",
      "  dispose() { this.listeners.clear(); }",
      "}",
      "class TreeItem {} class ThemeIcon {}",
      "const activeDocument = { fileName: 'active.json', uri: { scheme: 'file', fsPath: 'active.json' } };",
      "const vscode = {",
      "  EventEmitter, TreeItem, ThemeIcon,",
      "  TreeItemCollapsibleState: { None: 0, Collapsed: 1, Expanded: 2 },",
      "  l10n: { t: value => value },",
      "  window: { activeTextEditor: { document: activeDocument } },",
      "  Uri: class Uri {}",
      "};",
      "Module._load = function(request, ...args) {",
      "  return request === 'vscode' ? vscode : originalLoad.call(this, request, ...args);",
      "};",
      "const calls = []; let invalidations = 0;",
      "const model = {",
      "  invalidate() { invalidations++; },",
      "  getRoots: async (document, resource) => { calls.push({ document, resource }); return []; }",
      "};",
      "const focused = {",
      "  target: { kind: 'texture', id: 'demo:block/stone' },",
      "  producer: { producerId: 'physical:texture:stone' }",
      "};",
      "const rebound = { ...focused, producer: { ...focused.producer, revision: 'r2' } };",
      "const { ResourceGraphTreeProvider } = require(modulePath);",
      "let current = rebound;",
      "const provider = new ResourceGraphTreeProvider(model, (producerId, target) => {",
      "  assert.strictEqual(producerId, focused.producer.producerId);",
      "  assert.deepStrictEqual(target, focused.target);",
      "  return current;",
      "});",
      "let refreshes = 0; provider.onDidChangeTreeData(() => refreshes++);",
      "const focusStates = []; provider.onDidChangeFocus(value => focusStates.push(value));",
      "const wait = delay => new Promise(resolve => setTimeout(resolve, delay));",
      "(async () => {",
      "  provider.refreshActiveEditor();",
      "  assert.strictEqual(refreshes, 1);",
      "  provider.focusResource(focused);",
      "  assert.strictEqual(refreshes, 2);",
      "  provider.refreshActiveEditor();",
      "  assert.strictEqual(refreshes, 2, 'focused relations should not follow editor churn');",
      "  await provider.getChildren();",
      "  assert.strictEqual(calls[0].resource, rebound, 'focus should rebind to the current producer snapshot');",
      "  assert.strictEqual(provider.followActiveEditor(), true);",
      "  provider.refreshActiveEditor();",
      "  assert.strictEqual(refreshes, 4);",
      "  await provider.getChildren();",
      "  assert.strictEqual(calls[1].document, activeDocument);",
      "  assert.strictEqual(calls[1].resource, undefined);",
      "  assert.strictEqual(provider.followActiveEditor(), false);",
      "  provider.focusResource(focused); current = undefined;",
      "  await provider.getChildren();",
      "  assert.strictEqual(calls[2].resource, undefined, 'removed producers should fall back to the active editor');",
      "  assert.deepStrictEqual(focusStates, [true, false, true, false]);",
      "  provider.refreshSoon(0, true);",
      "  provider.refreshSoon(0, false);",
      "  await wait(10);",
      "  assert.strictEqual(invalidations, 1, 'a required inventory invalidation must survive a later presentation-only refresh');",
      "  provider.refreshSoon(0, false);",
      "  provider.refreshSoon(0, true);",
      "  await wait(10);",
      "  assert.strictEqual(invalidations, 2, 'either coalesced call order must retain inventory invalidation');",
      "  provider.refreshSoon(0, false);",
      "  await wait(10);",
      "  assert.strictEqual(invalidations, 2, 'a completed flush must reset the accumulated invalidation flag');",
      "  provider.refreshSoon(40, true);",
      "  provider.refresh();",
      "  assert.strictEqual(invalidations, 3, 'an immediate refresh owns and clears pending inventory invalidation');",
      "  await wait(50);",
      "  assert.strictEqual(invalidations, 3, 'the cancelled trailing refresh must not run after an immediate refresh');",
      "  provider.refreshSoon(40, true);",
      "  provider.dispose();",
      "  await wait(50);",
      "  assert.strictEqual(invalidations, 3, 'dispose must discard pending inventory invalidation');",
      "})().catch(error => { console.error(error); process.exitCode = 1; });"
    ].join("\n");

    const result = runTestProcessSync(process.execPath, ["-e", script, modulePath]);

    assertTestProcessStatus(result);
  });
});
