import { resolveFreshCompiledModule } from "../../../test/helpers/compiledHarness";
import {
  assertTestProcessStatus,
  defaultTestProcessMochaTimeoutMs,
  runTestProcessSync
} from "../../../test/helpers/testProcess";

describe("VS Code physical asset source exact resolution", function () {
  this.timeout(defaultTestProcessMochaTimeoutMs);

  it("uses canonical open-document identity and falls back on incomplete filesystem evidence", () => {
    const script = [
      "const assert = require('node:assert/strict');",
      "const Module = require('node:module'); const originalLoad = Module._load;",
      "class FileSystemError extends Error { constructor(code) { super(code); this.code = code; } }",
      "const uri = value => ({ value, scheme: value.slice(0, value.indexOf(':')), path: value.slice(value.indexOf(':') + 1), fsPath: value.slice(value.indexOf(':') + 1), query: '', fragment: '', toString: () => value });",
      "const joinUri = (base, ...segments) => uri(base.toString().replace(/\\/$/, '') + '/' + segments.join('/'));",
      "let statMode = 'ready'; let metadataMode = 'missing'; let statCalls = 0; let metadataReads = 0; let abortOnStat; let invalidateOnStat; let missingStatUris = new Set(); let directoryEntries = new Map(); let directoryReadCalls = 0; let textDocumentReads = 0;",
      "let openDocuments = [{ uri: uri('vscode-remote://ssh-remote+dev/work/%E8%B5%84%E6%BA%90/assets/demo/models/block/open.json') }];",
      "const workspace = { get textDocuments() { textDocumentReads++; return openDocuments; }, set textDocuments(value) { openDocuments = value; }, fs: {",
      "  stat: async target => { statCalls++; if (statMode === 'missing' || missingStatUris.has(target.toString())) throw new FileSystemError('FileNotFound'); if (statMode === 'unavailable') throw new Error('provider offline'); if (abortOnStat) { abortOnStat.abort(); abortOnStat = undefined; } if (invalidateOnStat) { const invalidate = invalidateOnStat; invalidateOnStat = undefined; invalidate(); } return { type: statMode === 'unknown' ? 0 : target.toString().endsWith('.json') || target.toString().endsWith('pack.mcmeta') ? 1 : 2 }; },",
      "  readFile: async target => { if (!target.toString().endsWith('pack.mcmeta')) return Buffer.from('{}'); metadataReads++; if (metadataMode === 'missing') throw new FileSystemError('FileNotFound'); if (metadataMode === 'unavailable') throw new Error('provider offline'); if (metadataMode === 'invalid') return Buffer.alloc(0); if (metadataMode === 'overlay') return Buffer.from(JSON.stringify({ overlays: { entries: [{ directory: 'overlay', formats: { min_inclusive: 1, max_inclusive: 999 } }] } })); if (metadataMode === 'targeted') return Buffer.from(JSON.stringify({ overlays: { entries: [{ directory: 'legacy', formats: [60, 64] }, { directory: 'current', min_format: [88, 0], max_format: [88, 0] }] } })); if (metadataMode === 'filterStack' && !target.toString().includes('/custom/')) return Buffer.from(JSON.stringify({ filter: { block: [{ namespace: 'demo', path: 'models/block/blocked\\\\.json' }] } })); if (metadataMode === 'externalFilterOnly' && target.toString().includes('/custom/')) return Buffer.from(JSON.stringify({ filter: { block: [{ namespace: 'demo', path: 'models/block/blocked\\\\.json' }] } })); return Buffer.from('{}'); },",
      "  readDirectory: async target => { directoryReadCalls++; return directoryEntries.get(target.toString()) ?? []; }",
      "} };",
      "Module._load = function(request, ...args) { if (request === 'vscode') return { Uri: { parse: uri, joinPath: joinUri }, FileType: { File: 1, Directory: 2 }, FileSystemError, workspace }; return originalLoad.call(this, request, ...args); };",
      "const { VscodePhysicalAssetSource } = require(process.argv[1]);",
      "const localLayer = { layerId: 'local', role: 'local', source: 'directory', rootUri: 'file:///pack', priority: 0, metadataRevision: 'm1' };",
      "const customLayer = { layerId: 'custom', role: 'custom', source: 'directory', rootUri: 'file:///custom', priority: 10, metadataRevision: 'm1' };",
      "const vanillaLayer = { layerId: 'vanilla', role: 'vanilla', source: 'directory', rootUri: 'file:///vanilla', priority: 20, metadataRevision: 'm1' };",
      "const context = { projectId: 'project', workspaceFolderUri: 'file:///pack', projectRootUri: 'file:///pack', packRootUri: 'file:///pack', assetsRootUri: 'file:///pack/assets', rsglSourceRootUris: ['file:///pack/rsgl'], outputPackRootUri: 'file:///pack', outputAssetsRootUri: 'file:///pack/assets', localLayer, externalLayers: [], overlaySelection: [], configurationRevision: 'c1', contextRevision: 'r1' };",
      "const source = new VscodePhysicalAssetSource({ getCachedContext: () => context });",
      "(async () => {",
      "  const open = await source.probeTargetUri('vscode-remote://ssh-remote+dev/work/%e8%b5%84%e6%ba%90/assets/demo/models/block/open.json');",
      "  assert.strictEqual(open, 'file'); assert.strictEqual(statCalls, 0);",
      "  workspace.textDocuments = []; statMode = 'missing';",
      "  assert.strictEqual(await source.probeTargetUri('file:///pack/missing.json'), 'missing');",
      "  statMode = 'unavailable';",
      "  assert.strictEqual(await source.probeTargetUri('file:///pack/offline.json'), 'unavailable');",
      "  statMode = 'unknown';",
      "  assert.strictEqual(await source.probeTargetUri('file:///pack/unknown.json'), 'unavailable');",
      "  statMode = 'ready'; metadataMode = 'unavailable';",
      "  assert.deepStrictEqual(await source.getOrderedAssetsRootUris(context, localLayer), { status: 'unavailable' });",
      "  metadataMode = 'missing';",
      "  assert.deepStrictEqual(await source.getOrderedAssetsRootUris(context, localLayer), { status: 'ready', assetsRootUris: ['file:///pack/assets'], filters: [] });",
      "  const cachedStatCalls = statCalls; const cachedMetadataReads = metadataReads;",
      "  assert.deepStrictEqual(await source.getOrderedAssetsRootUris(context, localLayer), { status: 'ready', assetsRootUris: ['file:///pack/assets'], filters: [] });",
      "  assert.strictEqual(statCalls, cachedStatCalls); assert.strictEqual(metadataReads, cachedMetadataReads);",
      "  source.invalidateProjects(['project']);",
      "  await source.getOrderedAssetsRootUris(context, localLayer);",
      "  assert.ok(statCalls > cachedStatCalls); assert.ok(metadataReads > cachedMetadataReads);",
      "  source.invalidateProjects(['project']);",
      "  const exactRequest = { context, target: { kind: 'model', id: 'demo:block/repeated' }, scope: 'effective' };",
      "  const firstExact = await source.resolveExactDefinition(exactRequest); const exactStatCalls = statCalls; const exactMetadataReads = metadataReads;",
      "  assert.strictEqual(firstExact.status, 'resolved'); assert.strictEqual(firstExact.definition.layer.layerId, 'local');",
      "  const secondExact = await source.resolveExactDefinition(exactRequest);",
      "  assert.deepStrictEqual(secondExact, firstExact); assert.strictEqual(statCalls, exactStatCalls); assert.strictEqual(metadataReads, exactMetadataReads);",
      "  source.invalidateProjects(['project']); await source.resolveExactDefinition(exactRequest);",
      "  assert.ok(statCalls > exactStatCalls); assert.ok(metadataReads > exactMetadataReads);",
      "  source.invalidateProjects(['project']);",
      "  const racingRequest = { context, target: { kind: 'model', id: 'demo:block/racing' }, scope: 'effective' };",
      "  invalidateOnStat = () => source.invalidateProjects(['project']);",
      "  await source.resolveExactDefinition(racingRequest); const racingStatCalls = statCalls;",
      "  await source.resolveExactDefinition(racingRequest);",
      "  assert.ok(statCalls > racingStatCalls, 'an invalidated in-flight probe must not repopulate the exact cache');",
      "  source.invalidateProjects(['project']); metadataMode = 'overlay';",
      "  const roots = ['file:///pack/overlay/assets', 'file:///pack/assets']; directoryEntries = new Map();",
      "  for (const root of roots) { directoryEntries.set(root, [['demo', 2]]); directoryEntries.set(root + '/demo', [['models', 2]]); directoryEntries.set(root + '/demo/models', [['block', 2]]); directoryEntries.set(root + '/demo/models/block', [['winner.json', 1]]); }",
      "  const textDocumentReadsBeforeOverlayScan = textDocumentReads; const directoryReadsBeforeOverlayScan = directoryReadCalls;",
      "  const overlayScan = await source.scanProject({ projectId: 'project', scope: { projectId: 'project' } }, new AbortController().signal);",
      "  assert.strictEqual(overlayScan.coverage.status, 'authoritative'); assert.deepStrictEqual(overlayScan.documents.map(document => document.uri), ['file:///pack/overlay/assets/demo/models/block/winner.json'], 'full snapshots must keep the same first-root winner as exact Definition');",
      "  assert.strictEqual(textDocumentReads - textDocumentReadsBeforeOverlayScan, 1, 'one scan must snapshot open documents once instead of probing the array per file');",
      "  assert.strictEqual(directoryReadCalls - directoryReadsBeforeOverlayScan, 8, 'breadth-first discovery must visit each reachable directory once');",
      "  directoryEntries.set('file:///pack/overlay/assets/demo/models/block', []);",
      "  workspace.textDocuments = [{ uri: uri('file:///pack/overlay/assets/demo/models/block/winner.json'), fileName: '/pack/overlay/assets/demo/models/block/winner.json', languageId: 'json', version: 1, getText: () => '{}' }];",
      "  const textDocumentReadsBeforeOpenOverlayScan = textDocumentReads;",
      "  const openOverlayScan = await source.scanProject({ projectId: 'project', scope: { projectId: 'project' } }, new AbortController().signal);",
      "  assert.deepStrictEqual(openOverlayScan.documents.map(document => document.uri), ['file:///pack/overlay/assets/demo/models/block/winner.json'], 'an open overlay document must outrank an enumerated base file');",
      "  assert.strictEqual(textDocumentReads - textDocumentReadsBeforeOpenOverlayScan, 1, 'open-document reuse must not rescan the workspace document array while loading files');",
      "  workspace.textDocuments = []; source.invalidateProjects(['project']); metadataMode = 'targeted'; context.targetPackFormat = { major: 64, minor: 0 }; context.overlaySelection = [];",
      "  assert.deepStrictEqual(await source.getOrderedAssetsRootUris(context, localLayer), { status: 'ready', assetsRootUris: ['file:///pack/legacy/assets', 'file:///pack/assets'], filters: [] });",
      "  source.invalidateProjects(['project']); context.overlaySelection = ['current'];",
      "  assert.deepStrictEqual(await source.getOrderedAssetsRootUris(context, localLayer), { status: 'ready', assetsRootUris: ['file:///pack/current/assets', 'file:///pack/assets'], filters: [] }, 'an explicit context selection must override target-derived overlays');",
      "  delete context.targetPackFormat; context.overlaySelection = [];",
      "  source.invalidateProjects(['project']); metadataMode = 'filterStack'; context.externalLayers = [customLayer]; directoryEntries = new Map([",
      "    ['file:///custom/assets', [['demo', 2]]], ['file:///custom/assets/demo', [['models', 2]]], ['file:///custom/assets/demo/models', [['block', 2]]], ['file:///custom/assets/demo/models/block', [['blocked.json', 1]]]",
      "  ]);",
      "  const filteredScan = await source.scanProject({ projectId: 'project', scope: { projectId: 'project' } }, new AbortController().signal);",
      "  assert.strictEqual(filteredScan.coverage.status, 'authoritative'); assert.strictEqual(filteredScan.documents.length, 1);",
      "  assert.deepStrictEqual(filteredScan.documents[0].blockedByLayerIds, ['local'], 'filter.block facts must travel with lower-layer canonical documents');",
      "  context.externalLayers = [];",
      "  source.invalidateProjects(['project']); metadataMode = 'externalFilterOnly'; context.externalLayers = [customLayer]; context.vanillaLayer = vanillaLayer; missingStatUris = new Set(['file:///custom/assets']); directoryEntries = new Map([",
      "    ['file:///vanilla/assets', [['demo', 2]]], ['file:///vanilla/assets/demo', [['models', 2]]], ['file:///vanilla/assets/demo/models', [['block', 2]]], ['file:///vanilla/assets/demo/models/block', [['blocked.json', 1]]]",
      "  ]);",
      "  const filterOnlyScan = await source.scanProject({ projectId: 'project', scope: { projectId: 'project' } }, new AbortController().signal);",
      "  assert.strictEqual(filterOnlyScan.coverage.status, 'authoritative'); assert.strictEqual(filterOnlyScan.documents.length, 1);",
      "  assert.deepStrictEqual(filterOnlyScan.documents[0].blockedByLayerIds, ['custom'], 'a metadata-only pack without assets must still filter lower layers');",
      "  context.externalLayers = []; delete context.vanillaLayer; missingStatUris = new Set();",
      "  source.invalidateProjects(['project']); metadataMode = 'invalid'; directoryEntries = new Map();",
      "  const invalidMetadataScan = await source.scanProject({ projectId: 'project', scope: { projectId: 'project' } }, new AbortController().signal);",
      "  assert.strictEqual(invalidMetadataScan.coverage.status, 'authoritative', 'malformed metadata cannot activate overlays and must not make enumerable base assets partial');",
      "  source.invalidateProjects(['project']);",
      "  const cancellation = new AbortController(); abortOnStat = cancellation;",
      "  await assert.rejects(source.getOrderedAssetsRootUris(context, localLayer, cancellation.signal), error => error?.name === 'AbortError');",
      "  metadataMode = 'unavailable'; directoryEntries = new Map();",
      "  const scan = await source.scanProject({ projectId: 'project', scope: { projectId: 'project' } }, new AbortController().signal);",
      "  assert.strictEqual(scan.coverage.status, 'partial');",
      "})().catch(error => { console.error(error); process.exitCode = 1; });"
    ].join("\n");
    const sourcePath = resolveFreshCompiledModule(
      "src/resourceUniverse/providers/vscodePhysicalAssetSource.ts"
    );
    const result = runTestProcessSync(process.execPath, ["-e", script, sourcePath]);
    assertTestProcessStatus(result);
  });
});
