import { combinedVsixArtifactNames } from "./combined-vsix-artifact-names.mjs";

export const measurementsDirectory = "dist/measurements";

const inMeasurements = fileName => `${measurementsDirectory}/${fileName}`;

/**
 * Canonical defaults for the measurement pipeline. The paired baseline VSIX
 * is a reviewed external A-arm artifact and is intentionally not generated by
 * any script; pass --baseline when refreshing that evidence.
 */
export const measurementPaths = Object.freeze({
  combinedVsix: Object.freeze({
    directory: measurementsDirectory,
    development: inMeasurements(combinedVsixArtifactNames.development),
    production: inMeasurements(combinedVsixArtifactNames.production),
    report: inMeasurements("combined-vsix-comparison.json")
  }),
  activationProbe: Object.freeze({
    nodeBundle: inMeasurements("json-only-activation.node-bundle.json"),
    extensionHost: inMeasurements("json-only-activation.extension-host.json")
  }),
  pairedActivation: Object.freeze({
    baselineVsix: "dist/minecraft-resourcepack-helper-final-a.vsix",
    candidateVsix: inMeasurements(combinedVsixArtifactNames.production),
    report: inMeasurements("json-only-activation-comparison.json"),
    verification: inMeasurements("json-only-activation-comparison-verification.json")
  }),
  activationBudget: Object.freeze({
    baseline: inMeasurements("json-only-activation.baseline.extension-host.json"),
    candidate: inMeasurements("json-only-activation.combined-production.extension-host.json"),
    report: inMeasurements("json-only-activation-budget.json")
  }),
  resourceUniverse: Object.freeze({
    report: inMeasurements("resource-universe-benchmark.json")
  })
});
